version: "3.9"

services:
  prompt-framework:
    build: .
    container_name: prompt_framework
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./src:/app
    working_dir: /app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    depends_on:
      - db
    command: uvicorn prompt_framework.app:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  pgdata:
